export component HeroDivider inherits Rectangle {
    width: 420px;
    height: 10px;
    background: transparent;

    Rectangle {
        width: 190px;
        height: 2px;
        x: 0px;
        y: 4px;
        background: #ff7a18;
    }

    Rectangle {
        width: 10px;
        height: 10px;
        x: 205px;
        y: 0px;
        border-radius: 5px;
        background: #ff7a18;
    }

    Rectangle {
        width: 190px;
        height: 2px;
        x: 230px;
        y: 4px;
        background: #ff7a18;
    }
}